# Generated by Django 3.2.6 on 2021-09-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.TextField()),
                ('machine_make', models.TextField()),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField()),
            ],
        ),
    ]
