# Generated by Django 3.2.6 on 2021-09-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_rename_machines_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('operator_name', models.CharField(max_length=200)),
                ('maintenance_personnel', models.CharField(max_length=200)),
                ('issue', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='service_comments',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_make',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(max_length=50),
        ),
    ]
