# Generated by Django 3.2.6 on 2021-09-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_rename_machine_machineservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinereport',
            name='report_date',
            field=models.DateField(default='2021-09-04'),
            preserve_default=False,
        ),
    ]
